### ISSUE TITLE
WPT: Add IDL for this module to WPT interface tests

### ISSUE THREAD

**Issue by ddorwin** [immersive-web/webxr-gamepads-module#10]
When this module was split from the core spec, the relevant IDL was [removed](https://github.com/web-platform-tests/wpt/pull/18267/files) from the [webxr.idl file](https://github.com/web-platform-tests/wpt/commits/master/interfaces/webxr.idl) used for the WPT idlharness tests. Thus, there is now no coverage for the IDL defined in this module in WPTs.

Something probably needs to be configured to extract IDL from this module and then run that IDL.

**Comment by Manishearth** [comment]
web-platform-tests/wpt#19169
web-platform-tests/wpt#19170
