### ISSUE TITLE
Is xr-standard's button 0 meant just for triggers or also for other primary buttons?

### ISSUE THREAD

**Issue by thetuvix** [immersive-web/webxr-gamepads-module#17]
> Also I think we were intending a restriction that the first entry must be a trigger not a face button.
> 
> So perhaps just:
> * Primary Trigger
> * Primary Squeeze
> * Primary Touchpad
> * Primary Thumbstick
> 
> WDYT?  Too confusing?

_Originally posted by @NellWaliczek in https://github.com/immersive-web/webxr-gamepads-module/pull/14_

**Comment by Manishearth** [comment]
Both I and @toji feel like the answer here is "yes"

**Comment by NellWaliczek** [comment]
@thetuvix I'm inclined to agree with Brandon on this one, but I want to make sure you're ok with the change since you had some concerns when originally discussed.

**Comment by thetuvix** [comment]
Sounds good to me.  I can make a small PR to fix this up.

**Comment by Manishearth** [comment]
Does Daydream's clicky thing count as a trigger?

**Comment by toji** [comment]
No. Daydream's main button is the touchpad. It will be mapped to `buttons[2]`, but still fire the `select` events. The app and home buttons are reserved by the UA and OS respectively.

![](http://ptgmedia.pearsoncmg.com/images/chap3_9780134845517/elementLinks/03fig01.jpg)

Yes. This is profoundly weird. At this point it's a [self correcting problem](https://www.theverge.com/2019/10/15/20915609/google-pixel-4-no-daydream-support-view-vr-headset-discontinued), though.

**Comment by Manishearth** [comment]
@toji hmm, the PR [here](https://github.com/immersive-web/webxr-gamepads-module/pull/24/) is requiring a primary trigger at `buttons[0]`, should that be changed?

**Comment by toji** [comment]
No, that should be fine for two reasons:

 1. The Daydream controller will not report itself as `xr-standard`, and that text only applies to `xr-standard` devices.
 1. `select` events are not explicitly bound to only a primary trigger, which is why we have all the language about identifying a "primary (select) action".

**Comment by Manishearth** [comment]
Sounds good. I was careful to make sure that PR implies that the primary trigger/squeeze MUST trigger the primary actions, but others may as well.

**Comment by toji** [comment]
Seems like this can be closed now that #24 is merged.

**Comment by thetuvix** [comment]
I'm fine for now to run with the `onselect` and `onsqueeze` events and hope that most sites power their UIs with those rather than Gamepad buttons, given the group's broader decisions around not surfacing Gamepad instances for non-controllers, such as detected hands.  However, my background concern remains that we're drawing a somewhat arbitrary distinction between "buttons" from hands (e.g. select/squeeze) and "buttons" from controllers (e.g. select/squeeze) that may lead to a split which web content supports which headsets.

If we ultimately find that too much WebXR content is making assumptions about physical gamepads specifically, UAs on hand-focused devices like HoloLens may be forced to implement virtual "Gamepads" to get content compatibility.  That would be a key data point for us to ensure WebXR's post-Gamepad input API better unifies controller and hand input.
