### ISSUE TITLE
negative value for gamepad id

### ISSUE THREAD

**Issue by ylafon** [immersive-web/webxr-gamepads-module#27]
While looking at https://github.com/w3ctag/design-reviews/issues/430 during our F2F, we figure out that section 3.2 is mandating gamepad's index to be -1.
[Gamepad Index](https://w3c.github.io/gamepad/#dom-gamepad-index) definition states that it is a positive integer, so an issue must be files on Gamepad to document the delegation of identification of the gamepad when the index is negative (or with a specific value of -1).
You might also want to defined a specific value to achieve the same for the gamepad id.

**Comment by ylafon** [comment]
Just to reiterate, as negative values are in direct contradiction with the Gamepad spec, please work with them to figure out a way forward (allowing negative values with a "reserved" definition, register specific positive values for that or anything that would solve this conflict).
Thanks!

**Comment by Manishearth** [comment]
https://github.com/immersive-web/webxr-gamepads-module/issues/27

**Comment by himorin** [comment]
@toji @cabanier we have an answer from gamepads spec's editors as https://github.com/w3c/gamepad/pull/158#issuecomment-1888207277
is it possible to consider of fix within gamepads module of WebXR?

/cc @Manishearth

**Comment by Manishearth** [comment]
It seems like Gamepad told us to continue doing whatever we're doing so I'm not sure if there's anything more to be done here.

**Comment by himorin** [comment]
@Manishearth sorry for quite late catch.

Summary as below, please correct if something wrong

- [change made to Gamepads spec (w3c/gamepads#151)](https://github.com/w3c/gamepad/pull/151) and new [selecting an unused gamepad index](https://w3c.github.io/gamepad/#dfn-selecting-an-unused-gamepad-index) algorithm was introduced ([diff](https://github.com/w3c/gamepad/pull/151/files#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051R654))
- now, there is no positive integer restriction in [gamepad index](https://w3c.github.io/gamepad/#dom-gamepad-index), although [selecting an unused gamepad index](https://w3c.github.io/gamepad/#dfn-selecting-an-unused-gamepad-index) algorithm will return non-negative integer (0 or positive) values and [navigator.getGamepads()](https://w3c.github.io/gamepad/#dom-navigator-getgamepads) returns as array whose index starts from 0
- WebXR gamepads module does not take array of gamepads, just has single [readonly attribute Gamepad XRInputSource.gamepad](https://www.w3.org/TR/webxr-gamepads-module-1/#ref-for-xrinputsource%E2%91%A2) not array as Gamepad specification. Also, index -1 will be assigned if [target device is not exposed via navigator.getGamepads()](https://www.w3.org/TR/webxr-gamepads-module-1/#ref-for-dom-gamepad-index). No conflict or handling issue in this space, also device with index -1 is specific within WebXR space which will not conflict (by means of shared or reused) with any other specifications relying on Gamepad specification.

@ylafon  does above solve concern from design review point of view?

**Comment by ylafon** [comment]
LGTM, thanks for the heads up!

**Comment by himorin** [comment]
@ylafon Thank you for comment. Is it fine to close this issue as completed?

**Comment by ylafon** [comment]
Yes, thanks!
