### ISSUE TITLE
Merge GamepadMappingType to Gamepad spec

### ISSUE THREAD

**Issue by saschanaz** [immersive-web/webxr-gamepads-module#35]
https://immersive-web.github.io/webxr-gamepads-module/#xr-standard-gamepad-mapping

Currently there are two `GamepadMappingType` in the Web IDL world and this is confusing tools, resulting [the manual removal in webref for example](https://github.com/w3c/webref/blob/4292a7dbd9dbe8c10cfb498e48bb12c734c9c9a2/ed/idlpatches/webxr-gamepads-module.idl.patch#L23).

Could we follow what https://github.com/immersive-web/webxr-ar-module/issues/32 did to fix the situation?

**Comment by toji** [comment]
Posted a pull request for this to https://github.com/w3c/gamepad/pull/146
