### ISSUE TITLE
Button indices 1 and 2 swapped in the diagram

### ISSUE THREAD

**Issue by thetuvix** [immersive-web/webxr-gamepads-module#9]
In the picture of the two example `"xr-standard"` controllers, button indices 1 and 2 are swapped relative to the table.

**Comment by toji** [comment]
Doh! You're right. I'll get that sorted out ASAP.

**Comment by toji** [comment]
There. Thank goodness for SVG being editable as text. :) Fixed in ba5c049c8cd331aac8e0e3456ecad95d5cbc0f66 (Shh! Don't rat me out for skipping a PR on this one!)
